[package]
name = "rust-outbound-pg-v3"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Useful crate to handle errors.
anyhow = "1"
# General-purpose crate with common HTTP types.
http = "1.0.0"
# The Spin SDK.
spin-sdk = { path = "../.." }

